### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-ArturoAngonJose#2]
[GESTIÓN DE PROYECTOS DE SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-ArturoAngonJose/files/9418951/GESTION.DE.PROYECTOS.DE.SOFTWARE.pdf)

**Comment by bg55-a** [comment]
Calificación: 20%

**Comment by javiern-778** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
